@url = http://localhost:4000

### POST Create a new metric
POST {{url}}/metrics
Content-Type: application/json

{
    "createdAt": "2021-10-01",
    "type": "register",
    "username": "usernameTest",
    "metrics": {}
}
