//@url =https://metricsservice-production.up.railway.app
@url =http://localhost:4000

### POST Create register metric
POST {{url}}/metrics
Content-Type: application/json

{
    "createdAt": "2024-11-07",
    "type": "register",
    "username": "usernameTest",
    "metrics": {
      "event_time": 10000,
      "success": false
    }
}

### POST Create register metric with provider
POST {{url}}/metrics
Content-Type: application/json

{
  "createdAt": "2021-10-02",
  "type": "register_with_provider",
  "username": "usernameTest",
  "metrics": {
  }
}

### POST Create login metric
POST {{url}}/metrics
Content-Type: application/json

{
  "createdAt": "2021-10-11",
  "type": "login",
  "username": "usernameTest",
  "metrics": {
    "success": true,
    "averageLoginTime": 10

  }
}

### POST Create login with provider
POST {{url}}/metrics
Content-Type: application/json

{
  "createdAt": "2021-11-11",
  "type": "login_with_provider",
  "username": "usernameTest",
  "metrics": {
    "success": true
  }
}

### POST Create login with provider
POST {{url}}/metrics
Content-Type: application/json

{
  "createdAt": "2024-11-24",
  "type": "blocked",
  "username": "usernameTest",
  "metrics": {
    "blocked": true
  }
}

### GET register metrics
GET {{url}}/metrics?type=register
Content-Type: application/json

### GET register with provider metrics
GET {{url}}/metrics/register?type=register_with_provider
Content-Type: application/json

### GET login metrics
GET {{url}}/metrics/register?type=login
Content-Type: application/json

### GET login with provider metrics
GET {{url}}/metrics/register?type=login_with_provider
Content-Type: application/json

### POST Create location metric
POST {{url}}/metrics
Content-Type: application/json

{
  "createdAt": "2024-11-06",
  "type": "location",
  "username": "usernameTest",
  "metrics": {
    "latitude":-34.61315,
    "longitude":-58.37723
  }
}

### GET location metrics
GET {{url}}/metrics?type=location
Content-Type: application/json


### POST Create Auth Twitter metric
POST {{url}}/metrics
Content-Type: application/json

{
  "createdAt": "2024-11-30",
  "type": "twit",
  "username": "b",
  "metrics": {}
}

### GET Auth Twitter metrics
GET {{url}}/metrics?type=twit&auth=true
Content-Type: application/json


### POST Create hashtag metric
POST {{url}}/metrics
Content-Type: application/json

{
  "createdAt": "2024-11-27",
  "type": "hashtag",
  "username": "b",
  "metrics": {
    "hashtag": "test4"
  }
}

### POST Create password metric
POST {{url}}/metrics
Content-Type: application/json

{
  "createdAt": "2021-10-10",
  "type": "password",
  "username": "usernameTest",
  "metrics": {
    "success": true,
    "event_time": 20000

  }
}

